### ISSUE TITLE
Does not work when multiple div's have 'root: element'

### ISSUE THREAD

**Issue by s0kil** [Promo/just-carousel#2]
I have 3 sections with `.carousel`.
I Initialize JustCarousel

```
    app.carousel = new JustCarousel({
        root: document.querySelector('.carousel'),
        onChangePos: function (data) {
            console.log(data);
        }
    });
```

But it only runs on the 1st section, not all 3.

**Comment by Blackheart340** [comment]
Hi @DanielSokil 

I hope I can help you.
`document.querySelector` returns only one DOM element.
Perhaps you can select all your containers with `document.querySelectorAll`, iterate by them and pass each container in constructor.

**Comment by s0kil** [comment]
@Blackheart340 Silly mistake, Thank You!
